### ISSUE TITLE
Can Tare algorithm work with sensors having shorter range?

### ISSUE THREAD

**Issue by madrid30** [caochao39/tare_planner#12]
I was checking the algorithm performance with short range in simulation (< 10 m). This condition is analogous to large range like 130 m when there are no features like vertical surfaces around in that range. The algorithm doesn't seems performing well.
Specially in outdoor conditions when there are no features in the sensor range to extract. The robot runs for some meter to cover surfaces and returns back where it started.   
Some information on this will be really helpful.

**Comment by caochao39** [comment]
Hi, the current version of the algorithm is designed for ground vehicles to cover vertical surfaces/frontiers (frontiers resulting from holes in the ceiling or on the ground are discarded). You might need to modify the frontier detection code for your purpose.
