### ISSUE TITLE
Transplant to ARM computer->Tsp problem

### ISSUE THREAD

**Issue by ssssuxin** [caochao39/tare_planner#15]
Just attending graduated school in China.I'm new to slam.And I try to transplant tare_planner in arm computer.
     When I tried to replace the lib-"ortool" for TSP with other TSP code(genetic algorithm) ,here comes the problem.
     It works will when it get into the unexplored area.There is something worong with global TSP when it go to erase the green block.You can check it in this video=>https://www.bilibili.com/video/BV1a84y1z71P/?vd_source=ac35690367071c24c9819b0880251afa
     Can you give me some advices?I can't fully understand the meaning of the source code without the code comments.
     by the way,when I input the distance matrix into TSP code(genetic algorithm),I got a list of numbers. You can check it in the picture.And I have no idea which should be at the head of the vector.
Thank you very much!
[2022-10-14 19-11-07 的屏幕截图](https://user-images.githubusercontent.com/81097744/195834052-898d2093-2f3b-45bc-9783-c62ab241cb21.png)

**Comment by ssssuxin** [comment]
And I check it again today.it may has nothing to do with global planning.it's the mistake the local planner make.

**Comment by ssssuxin** [comment]
And finally,I achieve it!! That's amazing!

**Comment by Alex-Beh** [comment]
@ssssuxin do you manage to compile the project on ARM computer in the end?
