### ISSUE TITLE
Is ROS2 humble branch stable to be used?

### ISSUE THREAD

**Issue by Alex-Beh** [caochao39/tare_planner#19]
Hi @caochao39 , may I know is ros2 branch stable to be used? I have tried noetic branch in ROS 1 environment and everything run smoothly. However for ROS 2 Humble, sometimes the exploration node (purple node) will be sampled at the place which is reachable from current node. Besides, and it sometimes will stuck inside the function call [UpdateKeyposeGraph](https://github.com/caochao39/tare_planner/blob/a5645d7e456a194d45216617dc94b19e8a273768/src/tare_planner/src/sensor_coverage_planner/sensor_coverage_planner_ground.cpp#L1436) and [UpdateGlobalRepresentation](https://github.com/caochao39/tare_planner/blob/a5645d7e456a194d45216617dc94b19e8a273768/src/tare_planner/src/sensor_coverage_planner/sensor_coverage_planner_ground.cpp#L1427) for long time.

**Comment by caochao39** [comment]
Yes.
