### ISSUE TITLE
Doesn't Compile in ARM

### ISSUE THREAD

**Issue by joshs333** [caochao39/tare_planner#3]
I would like to deploy this on a jetson xavier, having more issues with the pre-compiled binaries that are committed to the repo

**Comment by caochao39** [comment]
You can (hopefully) easily replace the tsp solver from OR-Tools with [this](http://webhotel4.ruc.dk/~keld/research/LKH/). Pull requests are welcome:)

**Comment by caochao39** [comment]
Hi, you can check out the ortools-9.6 branch and try the cross-compilation option for Arm https://github.com/google/or-tools/blob/stable/arm.sh

**Comment by xiao-yuhan** [comment]
You can try replacing it with the corresponding version of the OR-Tools file. Currently, tare is using the OR-Tools version 9.8.3296, and the **Jetson Ubuntu 20.04** system can replace the **Debian arm** version of OR-Tools and successfully compile, as mentioned in the README.
