### ISSUE TITLE
Question about the code for trajectory optimization in Algorithm2 mentioned in your paper about “TARE”

### ISSUE THREAD

**Issue by windlives** [caochao39/tare_planner#4]
hi, I have read your paper about "tare”, in which mention that there is a trajectory optimization part in local planner. but it seems that that part  is absent in this code. So did you haven't add it yet?

**Comment by caochao39** [comment]
Hi, thank you for your interest. The current open-sourced version is for ground vehicles only, which does not include the trajectory optimization part. We might open-source the aerial version in the future.
