### ISSUE TITLE
compile error about OR-Tools

### ISSUE THREAD

**Issue by jackykongfz** [caochao39/tare_planner#5]
I have a problem with compiling your tare-planner. It is about OR-Tools, I have tried several methods to solve this problem but did not succeed (like upgrading gcc to 7.0...), can you help me about this?

tare_planner/src/tare_planner/or-tools/lib/libortools.so: undefined reference to `log2f@GLIBC_2.27'
collect2: error: ld returned 1 exit status
FUEL/tare_planner/src/tare_planner/CMakeFiles/tare_planner_node.dir/build.make:740: recipe for target '/home/jackykong/motionplanning/FUEL_ws/devel/lib/tare_planner/tare_planner_node' failed
make[2]: *** [/home/jackykong/motionplanning/FUEL_ws/devel/lib/tare_planner/tare_planner_node] Error 1
CMakeFiles/Makefile2:8724: recipe for target 'FUEL/tare_planner/src/tare_planner/CMakeFiles/tare_planner_node.dir/all' failed
make[1]: *** [FUEL/tare_planner/src/tare_planner/CMakeFiles/tare_planner_node.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Ellinier** [comment]
I had the same problem

**Comment by Ellinier** [comment]
I had the same problem when I try to compile the tare-planner on Ubuntu 16.04 with ROS Kinetic. But when I compile this repo on Ubuntu 18.04 with ROS Melodic, the error about OR-Tools disappeared, and the compilation succeed.

**Comment by jackykongfz** [comment]
> I had the same problem when I try to compile the tare-planner on Ubuntu 16.04 with ROS Kinetic. But when I compile this repo on Ubuntu 18.04 with ROS Melodic, the error about OR-Tools disappeared, and the compilation succeed.

Thanks for your information, I would change my environment to 18.04
