### ISSUE TITLE
how to compute the covered point of a viewpoint?

### ISSUE THREAD

**Issue by zhujinwen0924** [caochao39/tare_planner#6]
I read the code and got in trouble.I can not understand how to compute the covered point of a viewpoint.Anyone can help me?
你好,我阅读代码一段时间了,但有个问题一直没有弄懂.就是在计算一个视点的覆盖的时候,是如何计算的?雷达模型是如何使用起来用于计算视点的信息增益的?
盼回复,祝生活愉快.

**Comment by caochao39** [comment]
Hi, [this function](https://github.com/caochao39/tare_planner/blob/d9c539d289721ba429c10e692c44cf20e0452c31/src/tare_planner/include/lidar_model/lidar_model.h#L43) does the trick.
