### ISSUE TITLE
Integration with other SLAM Algorithms

### ISSUE THREAD

**Issue by derektan95** [caochao39/tare_planner#8]
Hi,

I wonder if this graph-based planner can work with other types of SLAM algorithms such as [RTABMap](https://github.com/introlab/rtabmap_ros)? It has the flexibility to allow us to map the scene with RGBD input, while localizing using 3D LiDAR input. It has the ability to output octomaps as well. Thanks.

**Comment by caochao39** [comment]
Hi, our platform and algorithms are compatible with these [SLAM algorithms](https://drive.google.com/file/d/1jW1jFDvRsUWcfivC6WWcHHdX-JDSzPGo/view). However, it should also be possible to add in other algorithms so long as the desired interfaces (topic names, types, frequencies, etc.) are provided. Please refer to [cmu-exploration.com](https://www.cmu-exploration.com/) for more information on the interfaces.
